sudo: required

language: c

services:
  - docker

before_install:
  - docker pull taotaohsu/helloworld-docker

script:
        - docker run taotaohsu/helloworld -v $TRAVIS_BUILD_DIR "ls $TRAVISBUILD_DIR && cd $TRAVIS_BUILD_DIR && autoreconf -i && ./configure && make -j8"
