sudo: required

language: c

services:
  - docker

before_install:
  - docker pull taotaohsu/helloworld-docker

script:
  - echo ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}
  - docker run taotaohsu/helloworld-docker -v ${TRAVIS_BUILD_DIR}:/tmp/repo "ls /tmp/repo && cd /tmp/repo && autoreconf -i && ./configure && make -j8"
