sudo: required

language: c

services:
  - docker

before_install:
  - docker pull taotaohsu/helloworld-docker

script:
  - echo ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}
  - docker run -v ${TRAVIS_BUILD_DIR}:/tmp/repo taotaohsu/helloworld-docker ls /tmp
