sudo: required

language: c

services:
  - docker

before_install:
  - docker pull taotaohsu/helloworld-docker

script:
  - docker run -v $TRAVIS_BUILD_DIR:/tmp/build_dir taotaohsu/helloworld-docker /bin/bash -c "cd /tmp/build_dir && autoreconf --install && ./configure && make -j8"
